// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABW96Sw05_2OsON_nkotsTpHNMiqMx39I',
    appId: '1:1070830866614:web:cf0bea092d91b5c3049617',
    messagingSenderId: '1070830866614',
    projectId: 'smart-h-ec86f',
    authDomain: 'smart-h-ec86f.firebaseapp.com',
    databaseURL: 'https://smart-h-ec86f-default-rtdb.firebaseio.com',
    storageBucket: 'smart-h-ec86f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk764earabyKZ1-JwE29U90JvO0PbyHCQ',
    appId: '1:1070830866614:android:12785bf730434274049617',
    messagingSenderId: '1070830866614',
    projectId: 'smart-h-ec86f',
    databaseURL: 'https://smart-h-ec86f-default-rtdb.firebaseio.com',
    storageBucket: 'smart-h-ec86f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqI_HwVnQ4du7U621gI7R5H98l32X_J54',
    appId: '1:1070830866614:ios:1e362fcc30e2702b049617',
    messagingSenderId: '1070830866614',
    projectId: 'smart-h-ec86f',
    databaseURL: 'https://smart-h-ec86f-default-rtdb.firebaseio.com',
    storageBucket: 'smart-h-ec86f.firebasestorage.app',
    iosBundleId: 'com.example.smartHomeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqI_HwVnQ4du7U621gI7R5H98l32X_J54',
    appId: '1:1070830866614:ios:1e362fcc30e2702b049617',
    messagingSenderId: '1070830866614',
    projectId: 'smart-h-ec86f',
    databaseURL: 'https://smart-h-ec86f-default-rtdb.firebaseio.com',
    storageBucket: 'smart-h-ec86f.firebasestorage.app',
    iosBundleId: 'com.example.smartHomeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABW96Sw05_2OsON_nkotsTpHNMiqMx39I',
    appId: '1:1070830866614:web:9e12bada917cff9d049617',
    messagingSenderId: '1070830866614',
    projectId: 'smart-h-ec86f',
    authDomain: 'smart-h-ec86f.firebaseapp.com',
    databaseURL: 'https://smart-h-ec86f-default-rtdb.firebaseio.com',
    storageBucket: 'smart-h-ec86f.firebasestorage.app',
  );

}